# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'esqueci.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(562, 273)
        self.frame = QtWidgets.QFrame(Form)
        self.frame.setGeometry(QtCore.QRect(0, 0, 561, 271))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setGeometry(QtCore.QRect(10, 150, 210, 30))
        self.label.setStyleSheet("font-size:16px;")
        self.label.setObjectName("label")
        self.lineEdit = QtWidgets.QLineEdit(self.frame)
        self.lineEdit.setGeometry(QtCore.QRect(10, 180, 541, 31))
        self.lineEdit.setStyleSheet("    width: 100%;\n"
"    padding: 6px 12px;\n"
"    font-size: 16px;\n"
"    font-weight: 400;\n"
"    line-height: 1.5;\n"
"    color: #212529;\n"
"    background-color: #fff;\n"
"    background-clip: padding-box;\n"
"    border: 1px solid #ced4da;\n"
"    appearance: none;\n"
"    border-radius: 6px;")
        self.lineEdit.setObjectName("lineEdit")
        self.line_2 = QtWidgets.QFrame(self.frame)
        self.line_2.setGeometry(QtCore.QRect(0, 40, 710, 16))
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.label_2 = QtWidgets.QLabel(self.frame)
        self.label_2.setGeometry(QtCore.QRect(10, 5, 371, 31))
        self.label_2.setStyleSheet("font-size:24px;")
        self.label_2.setObjectName("label_2")
        self.frame_2 = QtWidgets.QFrame(self.frame)
        self.frame_2.setGeometry(QtCore.QRect(10, 50, 541, 101))
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.label_3 = QtWidgets.QLabel(self.frame_2)
        self.label_3.setGeometry(QtCore.QRect(20, 30, 61, 21))
        self.label_3.setStyleSheet("font-size:16px;")
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.frame_2)
        self.label_4.setGeometry(QtCore.QRect(30, 60, 51, 21))
        self.label_4.setStyleSheet("font-size:16px;")
        self.label_4.setObjectName("label_4")
        self.lbl_usuario = QtWidgets.QLabel(self.frame_2)
        self.lbl_usuario.setGeometry(QtCore.QRect(90, 30, 451, 21))
        self.lbl_usuario.setStyleSheet("font-size:16px;")
        self.lbl_usuario.setText("")
        self.lbl_usuario.setObjectName("lbl_usuario")
        self.lbl_senha = QtWidgets.QLabel(self.frame_2)
        self.lbl_senha.setGeometry(QtCore.QRect(80, 60, 461, 21))
        self.lbl_senha.setStyleSheet("font-size:16px;")
        self.lbl_senha.setText("")
        self.lbl_senha.setObjectName("lbl_senha")
        self.pushButton = QtWidgets.QPushButton(self.frame)
        self.pushButton.setGeometry(QtCore.QRect(460, 220, 91, 31))
        self.pushButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton.setStyleSheet("    font-weight: 400;\n"
"    text-align: center;\n"
"    white-space: nowrap;\n"
"    vertical-align: middle;\n"
"color: #fff;\n"
"    background-color: #007bff;\n"
"    border-color: #007bff;\n"
"    border: 1px solid transparent;\n"
"    padding: 6px 12px;\n"
"    font-size: 16px;\n"
"    line-height: 1.5;\n"
"    border-radius: 4px;")
        self.pushButton.setObjectName("pushButton")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Encontre seu usuário"))
        self.label.setText(_translate("Form", "Digite seu nome completo:"))
        self.label_2.setText(_translate("Form", "Encontre seu usuário"))
        self.label_3.setText(_translate("Form", "Usuário:"))
        self.label_4.setText(_translate("Form", "Senha:"))
        self.pushButton.setText(_translate("Form", "Buscar"))
