# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'presencas.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets, uic


class Ui_widget(object):
    def setupUi(self, widget):
        widget.setObjectName("widget")
        widget.setWindowModality(QtCore.Qt.WindowModal)
        widget.resize(965, 674)
        widget.setMinimumSize(QtCore.QSize(965, 674))
        widget.setMaximumSize(QtCore.QSize(965, 674))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("dist/favicon.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        widget.setWindowIcon(icon)
        widget.setWindowOpacity(1.0)
        widget.setStyleSheet("background-color:#fff;")
        self.frame = QtWidgets.QFrame(widget)
        self.frame.setGeometry(QtCore.QRect(10, -20, 1021, 691))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.alert = QtWidgets.QLabel(self.frame)
        self.alert.setGeometry(QtCore.QRect(30, 20, 661, 41))
        self.alert.setMouseTracking(True)
        self.alert.setText("")
        self.alert.setObjectName("alert")
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setGeometry(QtCore.QRect(30, 50, 531, 81))
        self.label.setStyleSheet("font-size:42px;\n"
"font-weight:bold;\n"
"background:transparent;")
        self.label.setObjectName("label")
        self.label_4 = QtWidgets.QLabel(self.frame)
        self.label_4.setGeometry(QtCore.QRect(30, 140, 141, 41))
        self.label_4.setStyleSheet("font-size:24px;\n"
"font-weight:bold;\n"
"color:#454545;")
        self.label_4.setObjectName("label_4")
        self.label_3 = QtWidgets.QLabel(self.frame)
        self.label_3.setGeometry(QtCore.QRect(30, 120, 51, 16))
        self.label_3.setStyleSheet("background-color:#D9DC3B;\n"
"height:10px;\n"
"width:75px;")
        self.label_3.setText("")
        self.label_3.setObjectName("label_3")
        self.CodigoContrato = QtWidgets.QLineEdit(self.frame)
        self.CodigoContrato.setGeometry(QtCore.QRect(30, 180, 661, 51))
        self.CodigoContrato.setStyleSheet("border:none;\n"
"border-bottom:1px solid purple;\n"
"outline:none;\n"
"font-size:24px;\n"
"background:#E7D8E9\n"
"")
        self.CodigoContrato.setObjectName("CodigoContrato")
        self.label_2 = QtWidgets.QLabel(self.frame)
        self.label_2.setGeometry(QtCore.QRect(700, 0, 271, 801))
        self.label_2.setStyleSheet("background: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(0, 0, 0, 255), stop:1 rgba(255, 255, 255, 255))qlineargradient(spread:pad, x1:0.483, y1:0.216, x2:0.506, y2:0.994, stop:0 rgba(85, 0, 127, 255), stop:0.784091 rgba(25, 25, 25, 255))")
        self.label_2.setText("")
        self.label_2.setObjectName("label_2")
        self.frame_2 = QtWidgets.QFrame(self.frame)
        self.frame_2.setGeometry(QtCore.QRect(30, 250, 661, 381))
        self.frame_2.setStyleSheet("background:#232323")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.dezesseis = QtWidgets.QCheckBox(self.frame_2)
        self.dezesseis.setGeometry(QtCore.QRect(20, 300, 161, 17))
        self.dezesseis.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.dezesseis.setStyleSheet("font-size:16px;\n"
"background:transparent;\n"
"color:transparent;")
        self.dezesseis.setObjectName("dezesseis")
        self.treze = QtWidgets.QCheckBox(self.frame_2)
        self.treze.setGeometry(QtCore.QRect(180, 270, 161, 17))
        self.treze.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.treze.setStyleSheet("font-size:16px;\n"
"background:transparent;\n"
"color:transparent;")
        self.treze.setObjectName("treze")
        self.label_7 = QtWidgets.QLabel(self.frame_2)
        self.label_7.setGeometry(QtCore.QRect(10, 70, 271, 31))
        self.label_7.setStyleSheet("background:transparent;\n"
"color:#fff;\n"
"font-weight:bold;\n"
"font-size:24px")
        self.label_7.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_7.setObjectName("label_7")
        self.catorze = QtWidgets.QCheckBox(self.frame_2)
        self.catorze.setGeometry(QtCore.QRect(340, 270, 161, 17))
        self.catorze.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.catorze.setStyleSheet("font-size:16px;\n"
"background:transparent;\n"
"color:transparent;")
        self.catorze.setObjectName("catorze")
        self.quinze = QtWidgets.QCheckBox(self.frame_2)
        self.quinze.setGeometry(QtCore.QRect(500, 270, 161, 17))
        self.quinze.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.quinze.setStyleSheet("font-size:16px;\n"
"background:transparent;\n"
"color:transparent;")
        self.quinze.setObjectName("quinze")
        self.label_6 = QtWidgets.QLabel(self.frame_2)
        self.label_6.setGeometry(QtCore.QRect(0, 0, 661, 51))
        self.label_6.setStyleSheet("background:#252525;\n"
"color:#fff;\n"
"font-weight:bold;\n"
"font-size:24px")
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName("label_6")
        self.dezoito = QtWidgets.QCheckBox(self.frame_2)
        self.dezoito.setGeometry(QtCore.QRect(340, 300, 161, 17))
        self.dezoito.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.dezoito.setStyleSheet("font-size:16px;\n"
"background:transparent;\n"
"color:transparent;")
        self.dezoito.setObjectName("dezoito")
        self.label_5 = QtWidgets.QLabel(self.frame_2)
        self.label_5.setEnabled(False)
        self.label_5.setGeometry(QtCore.QRect(0, 0, 661, 391))
        self.label_5.setStyleSheet("background: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(0, 0, 0, 255), stop:1 rgba(255, 255, 255, 255))qlineargradient(spread:pad, x1:0.483, y1:0.216, x2:0.506, y2:0.994, stop:0 rgba(85, 0, 127, 255), stop:0.784091 rgba(25, 25, 25, 255))")
        self.label_5.setText("")
        self.label_5.setObjectName("label_5")
        self.label_10 = QtWidgets.QLabel(self.frame_2)
        self.label_10.setGeometry(QtCore.QRect(10, 130, 20, 41))
        self.label_10.setStyleSheet("background-color:#D9DC3B;\n"
"height:10px;\n"
"width:75px;")
        self.label_10.setText("")
        self.label_10.setObjectName("label_10")
        self.label_12 = QtWidgets.QLabel(self.frame_2)
        self.label_12.setGeometry(QtCore.QRect(10, 180, 20, 41))
        self.label_12.setStyleSheet("background-color:#D9DC3B;\n"
"height:10px;\n"
"width:75px;")
        self.label_12.setText("")
        self.label_12.setObjectName("label_12")
        self.label_11 = QtWidgets.QLabel(self.frame_2)
        self.label_11.setGeometry(QtCore.QRect(40, 180, 611, 31))
        self.label_11.setStyleSheet("background:transparent;\n"
"color:#fff;\n"
"font-weight:bold;\n"
"font-size:12px;\n"
"")
        self.label_11.setLineWidth(2)
        self.label_11.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_11.setObjectName("label_11")
        self.dez = QtWidgets.QCheckBox(self.frame_2)
        self.dez.setGeometry(QtCore.QRect(340, 240, 161, 17))
        self.dez.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.dez.setStyleSheet("font-size:16px;\n"
"background:transparent;\n"
"color:transparent;")
        self.dez.setObjectName("dez")
        self.dezenove = QtWidgets.QCheckBox(self.frame_2)
        self.dezenove.setGeometry(QtCore.QRect(500, 300, 161, 17))
        self.dezenove.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.dezenove.setStyleSheet("font-size:16px;\n"
"background:transparent;\n"
"color:transparent;")
        self.dezenove.setObjectName("dezenove")
        self.nove = QtWidgets.QCheckBox(self.frame_2)
        self.nove.setGeometry(QtCore.QRect(180, 240, 161, 17))
        self.nove.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.nove.setStyleSheet("font-size:16px;\n"
"background:transparent;\n"
"color:transparent;")
        self.nove.setObjectName("nove")
        self.onze = QtWidgets.QCheckBox(self.frame_2)
        self.onze.setGeometry(QtCore.QRect(500, 240, 161, 17))
        self.onze.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.onze.setStyleSheet("font-size:16px;\n"
"background:transparent;\n"
"color:transparent;")
        self.onze.setObjectName("onze")
        self.oito = QtWidgets.QCheckBox(self.frame_2)
        self.oito.setGeometry(QtCore.QRect(20, 240, 151, 17))
        self.oito.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.oito.setStyleSheet("font-size:16px;\n"
"background:transparent;\n"
"color:transparent;")
        self.oito.setObjectName("oito")
        self.doze = QtWidgets.QCheckBox(self.frame_2)
        self.doze.setGeometry(QtCore.QRect(20, 270, 161, 17))
        self.doze.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.doze.setStyleSheet("font-size:16px;\n"
"background:transparent;\n"
"color:transparent;")
        self.doze.setObjectName("doze")
        self.label_13 = QtWidgets.QLabel(self.frame_2)
        self.label_13.setGeometry(QtCore.QRect(0, 340, 661, 41))
        self.label_13.setStyleSheet("background:#252525;\n"
"color:#fff;\n"
"font-weight:bold;\n"
"font-size:16px")
        self.label_13.setAlignment(QtCore.Qt.AlignCenter)
        self.label_13.setObjectName("label_13")
        self.label_9 = QtWidgets.QLabel(self.frame_2)
        self.label_9.setGeometry(QtCore.QRect(40, 130, 591, 31))
        self.label_9.setStyleSheet("background:transparent;\n"
"color:#fff;\n"
"font-weight:bold;\n"
"font-size:12px;\n"
"")
        self.label_9.setLineWidth(2)
        self.label_9.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_9.setObjectName("label_9")
        self.dezessete = QtWidgets.QCheckBox(self.frame_2)
        self.dezessete.setGeometry(QtCore.QRect(180, 300, 161, 17))
        self.dezessete.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.dezessete.setStyleSheet("font-size:16px;\n"
"background:transparent;\n"
"color:transparent;")
        self.dezessete.setObjectName("dezessete")
        self.label_8 = QtWidgets.QLabel(self.frame_2)
        self.label_8.setGeometry(QtCore.QRect(130, 100, 41, 16))
        self.label_8.setStyleSheet("background-color:#D9DC3B;\n"
"height:10px;\n"
"width:75px;")
        self.label_8.setText("")
        self.label_8.setObjectName("label_8")
        self.label_15 = QtWidgets.QLabel(self.frame_2)
        self.label_15.setGeometry(QtCore.QRect(40, 240, 141, 16))
        self.label_15.setStyleSheet("font-size:16px;\n"
"background:transparent;\n"
"color:#fff;")
        self.label_15.setObjectName("label_15")
        self.label_16 = QtWidgets.QLabel(self.frame_2)
        self.label_16.setGeometry(QtCore.QRect(200, 240, 141, 16))
        self.label_16.setStyleSheet("font-size:16px;\n"
"background:transparent;\n"
"color:#fff;")
        self.label_16.setObjectName("label_16")
        self.label_17 = QtWidgets.QLabel(self.frame_2)
        self.label_17.setGeometry(QtCore.QRect(360, 240, 141, 16))
        self.label_17.setStyleSheet("font-size:16px;\n"
"background:transparent;\n"
"color:#fff;")
        self.label_17.setObjectName("label_17")
        self.label_18 = QtWidgets.QLabel(self.frame_2)
        self.label_18.setGeometry(QtCore.QRect(520, 240, 141, 16))
        self.label_18.setStyleSheet("font-size:16px;\n"
"background:transparent;\n"
"color:#fff;")
        self.label_18.setObjectName("label_18")
        self.label_19 = QtWidgets.QLabel(self.frame_2)
        self.label_19.setGeometry(QtCore.QRect(40, 270, 141, 16))
        self.label_19.setStyleSheet("font-size:16px;\n"
"background:transparent;\n"
"color:#fff;")
        self.label_19.setObjectName("label_19")
        self.label_20 = QtWidgets.QLabel(self.frame_2)
        self.label_20.setGeometry(QtCore.QRect(40, 300, 141, 16))
        self.label_20.setStyleSheet("font-size:16px;\n"
"background:transparent;\n"
"color:#fff;")
        self.label_20.setObjectName("label_20")
        self.label_21 = QtWidgets.QLabel(self.frame_2)
        self.label_21.setGeometry(QtCore.QRect(200, 270, 141, 16))
        self.label_21.setStyleSheet("font-size:16px;\n"
"background:transparent;\n"
"color:#fff;")
        self.label_21.setObjectName("label_21")
        self.label_22 = QtWidgets.QLabel(self.frame_2)
        self.label_22.setGeometry(QtCore.QRect(200, 300, 141, 16))
        self.label_22.setStyleSheet("font-size:16px;\n"
"background:transparent;\n"
"color:#fff;")
        self.label_22.setObjectName("label_22")
        self.label_23 = QtWidgets.QLabel(self.frame_2)
        self.label_23.setGeometry(QtCore.QRect(360, 270, 141, 16))
        self.label_23.setStyleSheet("font-size:16px;\n"
"background:transparent;\n"
"color:#fff;")
        self.label_23.setObjectName("label_23")
        self.label_24 = QtWidgets.QLabel(self.frame_2)
        self.label_24.setGeometry(QtCore.QRect(360, 300, 141, 16))
        self.label_24.setStyleSheet("font-size:16px;\n"
"background:transparent;\n"
"color:#fff;")
        self.label_24.setObjectName("label_24")
        self.label_25 = QtWidgets.QLabel(self.frame_2)
        self.label_25.setGeometry(QtCore.QRect(520, 270, 141, 16))
        self.label_25.setStyleSheet("font-size:16px;\n"
"background:transparent;\n"
"color:#fff;")
        self.label_25.setObjectName("label_25")
        self.label_26 = QtWidgets.QLabel(self.frame_2)
        self.label_26.setGeometry(QtCore.QRect(520, 300, 141, 16))
        self.label_26.setStyleSheet("font-size:16px;\n"
"background:transparent;\n"
"color:#fff;")
        self.label_26.setObjectName("label_26")
        self.DataPresenca = QtWidgets.QLineEdit(self.frame_2)
        self.DataPresenca.setEnabled(False)
        self.DataPresenca.setGeometry(QtCore.QRect(0, 60, 161, 51))
        self.DataPresenca.setStyleSheet("border:none;\n"
"border-bottom:none;\n"
"outline:none;\n"
"font-size:0px;\n"
"background:transparent;\n"
"")
        self.DataPresenca.setObjectName("DataPresenca")
        self.DiaSemana = QtWidgets.QLineEdit(self.frame_2)
        self.DiaSemana.setEnabled(False)
        self.DiaSemana.setGeometry(QtCore.QRect(170, 60, 161, 51))
        self.DiaSemana.setStyleSheet("border:none;\n"
"border:none;\n"
"outline:none;\n"
"font-size:0px;\n"
"background:transparent;")
        self.DiaSemana.setPlaceholderText("")
        self.DiaSemana.setObjectName("DiaSemana")
        self.IpComputador = QtWidgets.QLineEdit(self.frame_2)
        self.IpComputador.setEnabled(False)
        self.IpComputador.setGeometry(QtCore.QRect(330, 60, 161, 51))
        self.IpComputador.setStyleSheet("border:none;\n"
"border:none;\n"
"outline:none;\n"
"font-size:0px;\n"
"background:transparent;")
        self.IpComputador.setPlaceholderText("")
        self.IpComputador.setObjectName("IpComputador")
        self.Computador = QtWidgets.QLineEdit(self.frame_2)
        self.Computador.setEnabled(False)
        self.Computador.setGeometry(QtCore.QRect(10, 60, 161, 51))
        self.Computador.setStyleSheet("border:none;\n"
"border:none;\n"
"outline:none;\n"
"font-size:0px;\n"
"background:transparent;")
        self.Computador.setPlaceholderText("")
        self.Computador.setObjectName("Computador")
        self.label_5.raise_()
        self.label_7.raise_()
        self.label_6.raise_()
        self.label_10.raise_()
        self.label_12.raise_()
        self.label_11.raise_()
        self.label_13.raise_()
        self.label_9.raise_()
        self.label_8.raise_()
        self.label_15.raise_()
        self.label_16.raise_()
        self.label_17.raise_()
        self.label_18.raise_()
        self.label_19.raise_()
        self.label_20.raise_()
        self.label_21.raise_()
        self.label_22.raise_()
        self.label_23.raise_()
        self.label_24.raise_()
        self.label_25.raise_()
        self.label_26.raise_()
        self.dezessete.raise_()
        self.dezenove.raise_()
        self.nove.raise_()
        self.dezesseis.raise_()
        self.doze.raise_()
        self.treze.raise_()
        self.catorze.raise_()
        self.dezoito.raise_()
        self.dez.raise_()
        self.quinze.raise_()
        self.oito.raise_()
        self.onze.raise_()
        self.DataPresenca.raise_()
        self.DiaSemana.raise_()
        self.IpComputador.raise_()
        self.Computador.raise_()
        self.registrar = QtWidgets.QPushButton(self.frame)
        self.registrar.setGeometry(QtCore.QRect(30, 640, 131, 41))
        self.registrar.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.registrar.setMouseTracking(False)
        self.registrar.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.registrar.setStyleSheet("QPushButton{\n"
"background:#481658;\n"
"color:#fff;\n"
"border:none;\n"
"outline:none;\n"
"font-weight:bold;\n"
"font-size:16px;\n"
"}\n"
"QPushButton:hover{\n"
"cursor:pointer;\n"
"background:#481685\n"
"}")
        self.registrar.setObjectName("registrar")
        self.label_14 = QtWidgets.QLabel(self.frame)
        self.label_14.setGeometry(QtCore.QRect(710, 250, 251, 201))
        self.label_14.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.label_14.setStyleSheet("background:transparent;\n"
"filter: invert(1);")
        self.label_14.setText("")
        self.label_14.setPixmap(QtGui.QPixmap("E:/xampp/htdocs/presencas/assets/img/logo.webp"))
        self.label_14.setObjectName("label_14")
        self.fechar_alert = QtWidgets.QPushButton(self.frame)
        self.fechar_alert.setEnabled(False)
        self.fechar_alert.setGeometry(QtCore.QRect(650, 20, 41, 41))
        self.fechar_alert.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.fechar_alert.setMouseTracking(False)
        self.fechar_alert.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.fechar_alert.setAcceptDrops(False)
        self.fechar_alert.setStyleSheet("color:transparent;\n"
"border:none;")
        self.fechar_alert.setObjectName("fechar_alert")
        self.btnEsqueci = QtWidgets.QPushButton(self.frame)
        self.btnEsqueci.setGeometry(QtCore.QRect(30, 230, 101, 21))
        self.btnEsqueci.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnEsqueci.setStyleSheet("color: #007bff;\n"
"    text-decoration: none;\n"
"    background-color: transparent;\n"
"border:none;\n"
"outline:none;")
        self.btnEsqueci.setObjectName("btnEsqueci")
        self.label_27 = QtWidgets.QLabel(self.frame)
        self.label_27.setGeometry(QtCore.QRect(710, 290, 250, 200))
        self.label_27.setStyleSheet("background:transparent;")
        self.label_27.setText("")
        self.label_27.setPixmap(QtGui.QPixmap("logo.webp"))
        self.label_27.setObjectName("label_27")
        self.label_2.raise_()
        self.alert.raise_()
        self.label.raise_()
        self.label_4.raise_()
        self.label_3.raise_()
        self.CodigoContrato.raise_()
        self.frame_2.raise_()
        self.registrar.raise_()
        self.label_14.raise_()
        self.fechar_alert.raise_()
        self.btnEsqueci.raise_()
        self.label_27.raise_()

        self.retranslateUi(widget)
        QtCore.QMetaObject.connectSlotsByName(widget)

    def retranslateUi(self, widget):
        _translate = QtCore.QCoreApplication.translate
        widget.setWindowTitle(_translate("widget", "Dê sua presença"))
        self.label.setText(_translate("widget", "Dê sua presença"))
        self.label_4.setText(_translate("widget", "Usuário:"))
        self.CodigoContrato.setPlaceholderText(_translate("widget", "Exemplo: 423365 ou LUCASK (Não digite seu nome)"))
        self.dezesseis.setText(_translate("widget", "16:00"))
        self.treze.setText(_translate("widget", "13:00"))
        self.label_7.setText(_translate("widget", "INSTRUÇÕES"))
        self.catorze.setText(_translate("widget", "14:00"))
        self.quinze.setText(_translate("widget", "15:00"))
        self.label_6.setText(_translate("widget", "Marque seus horários"))
        self.dezoito.setText(_translate("widget", "18:00"))
        self.label_11.setText(_translate("widget", "Se você tem 1h de aula, então marque apenas um horário, por exemplo: se você fica de 08h às 09h, \n"
"então marque o horário de 08:00 às 09:00."))
        self.dez.setText(_translate("widget", "10:00"))
        self.dezenove.setText(_translate("widget", "19:00"))
        self.nove.setText(_translate("widget", "09:00"))
        self.onze.setText(_translate("widget", "11:00"))
        self.oito.setText(_translate("widget", "08:00"))
        self.doze.setText(_translate("widget", "12:00"))
        self.label_13.setText(_translate("widget", "Se ainda estiver com dúvidas chame seu educador(a)."))
        self.label_9.setText(_translate("widget", "Se você tem 2h de aula, então marque dois horários, por exemplo: se você fica de 08h às 10h, \n"
"então marque os horários de 08:00 às 09:00 e de 09:00 às 10:00."))
        self.dezessete.setText(_translate("widget", "17:00"))
        self.label_15.setText(_translate("widget", "De 08:00 às 09:00"))
        self.label_16.setText(_translate("widget", "De 09:00 às 10:00"))
        self.label_17.setText(_translate("widget", "De 10:00 às 11:00"))
        self.label_18.setText(_translate("widget", "De 11:00 às 12:00"))
        self.label_19.setText(_translate("widget", "De 12:00 às 13:00"))
        self.label_20.setText(_translate("widget", "De 16:00 às 17:00"))
        self.label_21.setText(_translate("widget", "De 13:00 às 14:00"))
        self.label_22.setText(_translate("widget", "De 17:00 às 18:00"))
        self.label_23.setText(_translate("widget", "De 14:00 às 15:00"))
        self.label_24.setText(_translate("widget", "De 18:00 às 19:00"))
        self.label_25.setText(_translate("widget", "De 15:00 às 16:00"))
        self.label_26.setText(_translate("widget", "De 19:00 às 20:00"))
        self.registrar.setText(_translate("widget", "REGISTRAR"))
        self.fechar_alert.setText(_translate("widget", "X"))
        self.btnEsqueci.setText(_translate("widget", "Esqueci meu usuário"))
